[tool.poetry]
name = 'lolesports_stats'
version = '0.1.0'
description = ''
authors = ['Victor Otieno Omondi <victor@slick.co.ke>']

[tool.poetry.dependencies]
python = '^3.7'
[tool.poetry.dev-dependencies]
mypy = "^0.761.0"
